### ISSUE TITLE
[BUG] Изменение инструмента нотного блока на harp при изменение блока травы под ним.

### ISSUE THREAD

**Issue by Venterok** [RuverQ/Mauris#1]
Если поставить нотный блок на траву и у него в blockdata'e инструмент не harp, то после того как трава изменится на грязь
инструмент станет harp.

[Скриншот](https://media.discordapp.net/attachments/441244803527606282/879330459836874792/unknown.png)

**Comment by RuverQ** [comment]
Я проверил у себя на локальном сервере (с последним ядром Pur Pur) и такого бага у меня не возникает. Возможно какие-то другие плагины препятствуют BlockPhysicsEvent'у. Можете, пожалуйста, предоставить список ваших плагинов?

**Comment by RuverQ** [comment]
Да, я выяснил проблему. В общем, мой метод onPhysics(BlockPhysicsEvent) мог отменятся по причине того, что тип маурис блока TRIPWIRE был включён. 

В общем, я починил это. Дайте мне знать сработало это или нет.

[Download Build Package](https://github.com/RuverQ/Mauris/actions/runs/1163091894)

**Comment by Venterok** [comment]
ок
