### ISSUE TITLE
[BUG] Блок типа Tripwire меняет blockdata'у в некоторых случаях

### ISSUE THREAD

**Issue by Venterok** [RuverQ/Mauris#2]
Если поставить несколько блоков типа Tripwire рядом или просто возле крючка, то они соединятся и поменяют blockdata'у.
Думаю скриншоты не требуются.

### Server Version - 1.17.1 PurPur

**Comment by RuverQ** [comment]
Исправлено! Правда другой баг может произойти, когда нитки меняют свою блок бату только у клиента, но это только у клиента, так что, я думаю всё нормально.
